theme: jekyll-theme-cayman
title: Natallia's Portfolio
description: Language specialist using data science 
owner:
  name: Natallia Casey
  email: natacasey@outlook.com
  linkedin: #natallia-casey-96b34264/
  github: natacasey
