theme: minima 
title: Natallia Casey's Portfolio
author: Natallia Casey
description: Language specialist in love with data science
github_username: natacasey
email: natacasey@outlook.com
linkedin_username: #natallia-casey-96b34264
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
title-logo: /images/transparent.png
minima:
  skin: dark
minima:
  social_links:
    linkedin: natallia-casey-96b34264
    github: natacasey

