theme: minima 
title: Natallia's Portfolio
author: Natallia Casey
description: Language specialist in love with data science
github_username: natacasey
email: natacasey@outlook.com
linkedin_username: #natallia-casey-96b34264
title-logo: /images/ORANGE.png
minima:
  skin: dark
minima:
  social_links:
    linkedin: natallia-casey-96b34264
    github: natacasey

