theme: minima 
title: Natallia's Portfolio
description: Language specialist in love with data science
github_username: natacasey
email: natacasey@domain.com
linkedin_username: #natallia-casey-96b34264

