theme: minima 
title: Natallia Casey's Portfolio
author: Natallia Casey
description: Language specialist in love with data science
<a href="https://github.com/natacasey/natacasey.github.io/blob/main/images/Project%20Manager%20Creative%20Professional%20Resume.pdf">Resume</a> 
github_username: natacasey
email: natacasey@outlook.com
linkedin_username: #natallia-casey-96b34264
title-logo: /images/transparent.png
minima:
  skin: dark
minima:
  social_links:
    linkedin: natallia-casey-96b34264
    github: natacasey

