theme: minima 
title: Natallia's Portfolio
author: Natallia Casey
description: Language specialist in love with data science
logo: [https://github.com/natacasey/natacasey.github.io/blob/main/_assets/n_casey.jpg]
github_username: natacasey
email: natacasey@outlook.com
linkedin_username: #natallia-casey-96b34264
minima:
  skin: classic
minima:
  social_links:
    linkedin: natallia-casey-96b34264
    github: natacasey

