theme: jekyll-theme-architect
title: Natallia's Portfolio
description: A language specialist using data science 
name: Natallia Casey
email: natacasey@outlook.com
linkedin: natallia-casey-96b34264
github: natacasey
