theme: jekyll-theme-dinky
title: Natallia's Portfolio
description: Language specialist in love with data science
github_username: natacasey
email: your-email@domain.com
linkedin_username:#natallia-casey-96b34264

